Feat/1/Setup Repository to Use Nodejs
ampazdev/accountservice pull request #3
Opened 2023-03-21 07:01 UTC by sarahaudina

close #1

2023-03-21 13:55 UTC, isfanazha requested changes
minor comment @sarahaudina

2023-03-21 13:55 UTC, isfanazha commented on src/common/guard/jwt.guard.ts
> +    //HACK not recommended though 😅
better to remove this comment 🤣 . maybe can use "//TODO: Need to improve the flow". So using "TODO:" comment, we can easily search which function needs to be improved hehe

2023-03-21 13:55 UTC, isfanazha commented on src/auth/auth.service.ts
> +    // const hashedInputPassword = await argon.hash(dto.password);
if it's unnecessary, just remove it hehe

2023-03-21 13:55 UTC, isfanazha commented on src/auth/auth.service.ts
> +      console.log('user:' + user.password);
remove unnecessary console log

2023-03-21 13:55 UTC, isfanazha commented on src/auth/auth.service.ts
> +        if (e.code === 'P2002') throw new BadRequestException('email is taken');
what is `P2002` , should we move it to the constant?

2023-03-21 14:05 UTC, sarahaudina commented on src/common/guard/jwt.guard.ts
> +    //HACK not recommended though 😅
🤣 noted 👌

2023-03-21 14:05 UTC, sarahaudina commented on src/auth/auth.service.ts
> +    // const hashedInputPassword = await argon.hash(dto.password);
sorry i just love hoarding unused code

2023-03-21 14:06 UTC, sarahaudina commented on src/auth/auth.service.ts
> +        if (e.code === 'P2002') throw new BadRequestException('email is taken');
its prisma error code for duplicate unique entity

2023-03-21 14:19 UTC, isfanazha commented on src/auth/auth.service.ts
> +    // const hashedInputPassword = await argon.hash(dto.password);
i see haha @sarahaudina

2023-03-21 14:50 UTC, sarahaudina commented on src/auth/auth.service.ts
> +    // const hashedInputPassword = await argon.hash(dto.password);
✌️

2023-03-24 08:37 UTC, sarahaudina commented
Updated with requested changes

2023-03-24 09:59 UTC, isfanazha commented
lgtm @sarahaudina

2023-03-24 10:00 UTC, isfanazha approved these changes

2023-03-28 09:44 UTC, merged